epcon<-read.csv2("household_power_consumption.txt",na.strings="?",dec=".",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
epcons<-subset(epcon,Date == "2/2/2007" | Date == "1/2/2007")
epcons$datetime<-strptime(datetime,"%d/%m/%Y %H:%M:%S")
png(filename="plot3.png")
plot(epcons$datetime,epcons$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(epcons$datetime,epcons$Sub_metering_2,type="l",col="red")
lines(epcons$datetime,epcons$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),lwd=c(2.5,2.5,2.5),col=c("black","red","blue"))
dev.off()